version: '3.8'

services:
  motiv_bot:
    build: .
    container_name: wisdom_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_API_URL=${DEEPSEEK_API_URL}
    volumes:
      - ./quotes.db:/app/quotes.db
    env_file:
      - .env
